version: '3.8'

services:
  backend:
    image: node:21-alpine3.17
    container_name: fs-app-backend
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    ports:
      - '3000:3000'
    command: sh -c "yarn && yarn dev"
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/myapp
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: fs-app-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  frontend:
    image: node:21-alpine3.17
    container_name: fs-app-frontend
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - '3001:3000'
    command: sh -c "yarn && yarn dev"

volumes:
  postgres_data:
